### PR TITLE
Feature/game timer

### PR DESCRIPTION
**Pull request by Lucas4185**

### CODE REVIEW

**Review by Mitchell-T — CHANGES_REQUESTED** [review]
Please remove the debugging statements in TimerSetup.cs and Timer.cs

**Review by Mitchell-T — APPROVED** [review]
LGTM!

**Review by SjorsMaster — CHANGES_REQUESTED** [review]
Please add some comments and remove commended code.

**Review by SjorsMaster — APPROVED** [review]
Looks good to me

**Pull request merged**
